export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const TOGGLE_ITEM = 'TOGGLE_ITEM';
export const DELETE_ALL_ITEMS = 'DELETE_ALL_ITEMS';
export const DELETE_COMPLETED_ITEMS = 'DELETE_COMPLETED_ITEMS';
export const DELETE_INCOMPLETE_ITEMS = 'DELETE_INCOMPLETE_ITEMS';
export const MARK_ALL_COMPLETE = 'MARK_ALL_COMPLETE';
export const EDIT_ITEM = 'EDIT_ITEM';
